import { useEffect, useState, type RefObject } from 'react';
import { api, fileSrc, isRemote, type Wallpaper } from './api';

/** Becomes true once the element scrolls near the viewport (and stays true). */
export function useInView(ref: RefObject<Element | null>, rootMargin = '400px'): boolean {
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el || inView) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setInView(true);
          observer.disconnect();
        }
      },
      { root: el.closest('.layout__content'), rootMargin },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [ref, inView, rootMargin]);
  return inView;
}

/**
 * Lightweight preview for a wallpaper: the remote thumbnail, a cached local thumbnail
 * generated by the backend, or (for local videos) the video file itself.
 */
export function useThumbSrc(wp: Wallpaper, enabled: boolean): { src?: string; video?: string } {
  const remoteThumb = isRemote(wp.thumbnail_url) ? wp.thumbnail_url : undefined;
  const localPath = wp.local_path ?? (isRemote(wp.url) ? undefined : wp.url);
  const needsLocalThumb = enabled && !remoteThumb && !!localPath && wp.media_type !== 'video';
  const [localThumb, setLocalThumb] = useState<string>();

  useEffect(() => {
    if (!needsLocalThumb || !localPath) return;
    let cancelled = false;
    api
      .getThumbnail(localPath)
      .then((p) => !cancelled && setLocalThumb(fileSrc(p)))
      .catch(() => !cancelled && setLocalThumb(fileSrc(localPath)));
    return () => {
      cancelled = true;
    };
  }, [needsLocalThumb, localPath]);

  if (!enabled) return {};
  if (remoteThumb) return { src: remoteThumb };
  if (localPath && wp.media_type === 'video') return { video: fileSrc(localPath) };
  if (!localPath && isRemote(wp.url)) return { src: wp.url };
  return { src: localThumb };
}
